// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsersManagement.Infrastructure.Context;

namespace UsersManagement.Infrastructure.Migrations
{
    [DbContext(typeof(UsersContext))]
    partial class UsersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UsersManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5997c8dc-b95e-45dc-a7b6-622f5d087da7"),
                            Email = "rony@mail.com",
                            IsActive = true,
                            Name = "Rony Cuzco",
                            Password = "Password12023"
                        },
                        new
                        {
                            Id = new Guid("42030bd2-0ec4-445a-84fd-71bee25e3405"),
                            Email = "julie@mail.com",
                            IsActive = true,
                            Name = "Julie Zarco",
                            Password = "Password12023"
                        },
                        new
                        {
                            Id = new Guid("37b89795-4297-4678-8193-c98470a721c2"),
                            Email = "ariadne@mail.com",
                            IsActive = true,
                            Name = "Ariadne Cuzco Zarco",
                            Password = "Password12023"
                        },
                        new
                        {
                            Id = new Guid("bf935030-aa9b-463f-8637-357ac08e8d1c"),
                            Email = "trufa@mail.com",
                            IsActive = true,
                            Name = "Truferia Zarco",
                            Password = "Password12023"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
