// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PostsRestApiService.Models
{
    [Table("User")]
    public partial class User
    {
        public User()
        {
            Posts = new HashSet<Post>();
        }

        [Key]
        public Guid UserId { get; set; }
        [StringLength(50)]
        public string UserNames { get; set; }

        [InverseProperty(nameof(Post.User))]
        public virtual ICollection<Post> Posts { get; set; }
    }
}