// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UsersRestApiService.Models
{
    [Table("User")]
    public partial class User
    {
        [Key]
        public Guid UserId { get; set; }
        [StringLength(50)]
        public string UserNames { get; set; }
        [StringLength(50)]
        public string UserLastName { get; set; }
        [StringLength(50)]
        public string UserEmail { get; set; }
    }
}